# autogenerated by txs
\mathsterling#S
\OML/lmm/b/it#S
\OML/lmm/m/it#S
\OMS/lmsy/b/n#S
\OMS/lmsy/m/n#S
\OMX/lmex/m/n#S
\OT1/lmr/bx/it#S
\OT1/lmr/bx/n#S
\OT1/lmr/m/it#S
\OT1/lmr/m/n#S
\OT1/lmss/bx/n#S
\OT1/lmss/m/n#S
\OT1/lmtt/m/n#S
