# autogenerated by txs
#include:\MD@default@family
#include:ifthen
#include:keyval
\ProcessUnusedOptions{arg1}#S
\WarningIfLoadedNoOption{arg1}{arg2}#S
\WarningIfLoaded{arg1}{arg2}#S
\ficshape{arg1}#S
\fscshape{arg1}#S
\selectgreekfamily{arg1}#S
\?\figurecircled#S
\MDB-cmd#S
\MDB\figurecircled#S
\WarningIfLoaded#S
\figurecircled#S
fontenc.sty#S
ifthen.sty#S
