# autogenerated by txs
#include:fontspec
#include:ifluatex
#include:ifxetex
#include:mweights
#include:xkeyval
\familydefault#S
\nativeoldstylenums#S
\seriesdefault#S
\ttdefault#S
fontenc.sty#S
ifxetex.sty#S
mweights.sty#S
xkeyval.sty#S
